name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 - name: Debug secrets
  run: |
    echo "DOCKER_USERNAME: $DOCKER_USERNAME"
    echo "DOCKER_PASSWORD is set: [${DOCKER_PASSWORD:+yes}]"
  env:
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app .

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app
